// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd22kR7krhAzxCCI7EZ42mPnOUAny5G0c',
    appId: '1:437255880758:web:5bc9f8f685a16189ee5897',
    messagingSenderId: '437255880758',
    projectId: 'fur-qr-project',
    authDomain: 'fur-qr-project.firebaseapp.com',
    storageBucket: 'fur-qr-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLkm2LSmuTvY4fu66e3j5rzQ8TsgYjf6E',
    appId: '1:437255880758:android:cfc174ad9c608b34ee5897',
    messagingSenderId: '437255880758',
    projectId: 'fur-qr-project',
    storageBucket: 'fur-qr-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKhny4E61ZKj8XlR2fyTzzcRd4wJy-eCk',
    appId: '1:437255880758:ios:349dda6c71d8dcb1ee5897',
    messagingSenderId: '437255880758',
    projectId: 'fur-qr-project',
    storageBucket: 'fur-qr-project.firebasestorage.app',
    iosBundleId: 'com.example.ownerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKhny4E61ZKj8XlR2fyTzzcRd4wJy-eCk',
    appId: '1:437255880758:ios:349dda6c71d8dcb1ee5897',
    messagingSenderId: '437255880758',
    projectId: 'fur-qr-project',
    storageBucket: 'fur-qr-project.firebasestorage.app',
    iosBundleId: 'com.example.ownerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd22kR7krhAzxCCI7EZ42mPnOUAny5G0c',
    appId: '1:437255880758:web:0b9a3e044ea30e88ee5897',
    messagingSenderId: '437255880758',
    projectId: 'fur-qr-project',
    authDomain: 'fur-qr-project.firebaseapp.com',
    storageBucket: 'fur-qr-project.firebasestorage.app',
  );
}
